### ISSUE TITLE
discord/automod/bot.py", line 221     async def on_ready(self):

### ISSUE THREAD

**Issue by commonsharp** [SexualRhinoceros/ModTools#4]
my pyver : Python 3.4.3+ (default, Oct 14 2015, 16:03:50) 
install log : http://pastebin.com/raw/xiPQUh4U
how can i fix it?
$ python3 run.py 
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from automod import AutoMod
  File "/home/user/discord/automod/__init__.py", line 1, in <module>
    from .bot import AutoMod
  File "/home/user/discord/automod/bot.py", line 221
    async def on_ready(self):

**Comment by commonsharp** [comment]
o..shit I see past issue now #3
